### ISSUE TITLE
Kan geen icoontjes toevoegen.

### ISSUE THREAD

**Issue by johannesdewit** [andredelft/heidegger-theme#1]
Ik probeer icoontjes toe te voegen a.d.h.v. de in de README gegeven instructies, maar dat lukt niet. Ik ben een complete node.js-noob, dus ik doe vast iets fout.

Ik heb node.js geïnstalleerd, en vervolgens in de root van de repo `npm install` gerund om het te installeren. Vervolgens de svg's van de icoontjes toevoegd en `npm run generate-icons` gerund. Ik krijg dan de volgende melding en geen verdere wijzigingen in de bestanden:

```sh
> heidegger-theme@1.0.0 generate-icons
> fantasticon

(node:1696) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
No SVGs found in ./assets
```

Omdat ik niet goed weet hoe ik node.js moet troubleshooten, meld ik het hier!

N.B. ik wilde phosphor-icons `arrow-square-in` en `arrow-square-out` toevoegen.

**Comment by andredelft** [comment]
Hmm, opmerkelijk. Mij lukt het wel. Wat zijn de versies van npm en node? Kun je zien met `npm -v` en `node -v`.

Werk je toevallig op een Windows? Ik ben daarop wel eens dit soort problemen tegengekomen.

**Comment by johannesdewit** [comment]
Ik werk inderdaad op windows nu. Ik zal het eens op MacOS proberen als ik thuis ben!

**Comment by andredelft** [comment]
Oke, ik heb daar wel een fix voor,ik ga er achteraan!

**Comment by andredelft** [comment]
Kijk even of #2 je probleem oplost!

**Comment by andredelft** [comment]
(Dat wil zeggen, doe een checkout op die branch, daarna opnieuw een `npm install`, en kijk of `npm run generate-icons` nu werkt.)
